# Generated by Django 6.0 on 2025-12-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
