# Generated by Django 6.0 on 2025-12-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_medicalreport_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='comparison_table',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
