# Generated by Django 6.0 on 2025-12-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_medicalreport_comparison_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='key_observations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
