# Generated by Django 6.0 on 2025-12-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_medicalreport_key_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='final_conclusion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
