# Generated by Django 6.0 on 2025-12-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_medicalreport_final_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='patient_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='vitals',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
