# Generated by Django 5.1.6 on 2025-12-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_medicalreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='blood_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='spo2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
