# Generated by Django 5.1.6 on 2025-12-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_medicalreport_blood_sugar_medicalreport_spo2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalreport',
            old_name='spo2',
            new_name='bmi',
        ),
        migrations.RenameField(
            model_name='medicalreport',
            old_name='blood_sugar',
            new_name='respiratory_rate',
        ),
    ]
