# Generated by Django 5.1.6 on 2025-12-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_rename_spo2_medicalreport_bmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='summary_pdf',
            field=models.FileField(blank=True, null=True, upload_to='report_summaries/'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
